on:
   push:


jobs:
    docker_build_job:
            - uses: ./.github/workflows/main.yml@build_workflow
              with:
                  inputs: ${{ github.repository }}
    artifact_uploads:
            - uses: ./.github/workflows/main.yml@upload_repo
              with:
                  inputs: ${{ github.repository }}

