on:
   push:

jobs:
    docker_build_job:
        runs-on: ubuntu-22.04
        name: Setup Container
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          
          - name: Run Continaer
            uses: ./.github/workflows/
            id: makepkg-container

          - name: Upload Artifacts
            uses: actions/upload-artifact@v3
            with:
             name: artifact_package
             path: "*.pkg.tar.zst"

    artifact_uploads:
        runs-on: ubuntu-22.04
        needs: docker_build_job
        name: Pushing
        steps:
          - name: Clone Repo 
            uses: actions/checkout@v3
            with:
              repository: ardentteams/ardent-repos
              path: repos
              ref: gh-pages
          - name: Download Artifacts
            uses: actions/download-artifact@v3
            with:
                name: artifact_package
          - name: Check download files
            run: ls -R
