on:
    workflow_call:
        inputs:
            branch_name:
                required: true
                type: string

jobs:
    docker_build_job:
        runs-on: ubuntu-22.04
        name: Setup Container
        steps:
          - name: Upload Artifacts
            uses: actions/upload-artifact@v3
            with:
             name: artifact_package
             path: "*.pkg.tar.zst"

