on:
    workflow_call:
        inputs:
            artifact_name:
                required: true
                type: string

jobs:
    artifact_uploads:
        runs-on: ubuntu-22.04
        needs: docker_build_job
        name: Pushing
        steps:
          - name: Clone Repo 
            uses: actions/checkout@v3
            with:
              repository: ardentteams/ardent-repos
              path: repos
              ref: gh-pages
          - name: Download Artifacts
            uses: actions/download-artifact@v3
            with:
                name: ${{ inputs.artifact_name }}
          - name: Check download files
            run: ls -R
