on:
    workflow_call:
        inputs:
            name:
                require: true
                type: string

jobs:
    docker_build_job:
        runs-on: ubuntu-22.04
        name: Setup Container
        steps:
          - name: Checkout
            uses: actions/checkout@v3
                repository: ${{ inputs.name }}

          - name: Run Continaer
            uses: ./.github/workflows/
            id: makepkg-container

          - name: Upload Artifacts
            uses: actions/upload-artifact@v3
            with:
             name: artifact_package
             path: "*.pkg.tar.zst"

