on:
    workflow_call:
        inputs:
            branch_name:
                required: true
                type: string

jobs:
    docker_build_job:
        runs-on: ubuntu-22.04
        name: Setup Container
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                ref: build_workflow
                path: .github/actions/build_workflow

          - name: Run Continaer
            uses: ./.github/actions/build_workflow/.github/workflows/main.yml
               id: makepkg-container

          - name: Upload Artifacts
            uses: actions/upload-artifact@v3
            with:
             name: artifact_package
             path: "*.pkg.tar.zst"

